- name: Build dmm-gacha
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - dmm_secrets.yml
  roles:
    - role: lein_build 

- name: Deploy dmm-gacha
  hosts:
    - webservers
    - tag_type_web
  vars_files:
    - dmm_secrets.yml
  become: True
  roles:
    - role: deploy_jar
