- name: Build genegacha
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - genegacha_secrets.yml
  roles:
    - role: lein_build

- name: Deploy genegacha
  hosts:
    - webservers
    - tag_type_web
  vars_files:
    - genegacha_secrets.yml
  become: True
  roles:
    - role: deploy_html
