- name: build jar
  hosts: 127.0.0.1
  connection: local
  vars_files:
    genegacha_secrets.yml
  tasks:
    - name: clean target directory
      command: /usr/local/bin/lein clean
      args:
        chdir: "{{ local_home }}"
    - name: production build
      command: /usr/local/bin/lein prod
      args:
        chdir: "{{ local_home }}"

- name: Deploy genegacha
  hosts:
    - webservers
    - tag_type_web
  vars_files:
    - genegacha_secrets.yml
  become: True
  tasks:
    - name: install apt packages
      apt:
        pkg:
          - nginx
        update_cache: yes
        cache_valid_time: 3600

    - name: create project directory
      file: path="{{ home_dir }}" state=directory

    - name: copy build files
      copy:
        src: "{{ local_home }}/resources/public/"
        dest: "{{ home_dir }}"
        mode: "0755"

    - name: copy nginx config file
      template:
        src: "templates/nginx-static.conf.j2"
        dest: "/etc/nginx/sites-available/{{ nginx_file }}"
      notify: "restart nginx"

    - name: enable configuration
      file:
        dest: "/etc/nginx/sites-enabled/{{ nginx_file }}"
        src: "/etc/nginx/sites-available/{{ nginx_file }}"
        state: link
      notify: "restart nginx"

  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
      listen: "restart nginx"
