- name: Dump a database on local
  hosts: 127.0.0.1
  connection: local
  vars_files:
    - hpdb_secrets.yml
  roles:
    - role: dump_postgres

- name: Initialize postgres
  hosts:
    - webservers
  vars_files:
    - hpdb_secrets.yml
  become: True
  roles:
    - role: init_postgres
