- name: install apt packages
  apt:
    pkg:
      - openjdk-8-jdk
      - nginx
      - supervisor
    update_cache: yes
    cache_valid_time: 3600        
- name: create project directory
  file: path="{{ home_dir }}" state=directory
- name: copy dmm-gacha jar
  copy:
    src: "{{ local_home }}/target/{{ artifact }}"
    dest: "{{ home_dir }}/{{ artifact }}"
    mode: "0755"
  notify: "restart web server"
- name: set the supervisor
  template:
    src: "supervisor.conf.j2"
    dest: "/etc/supervisor/conf.d/{{ conf_file }}"
  notify: "restart web server"
- name: copy nginx config file
  template:
    src: "nginx.conf.j2"
    dest: "/etc/nginx/sites-available/{{ conf_file }}"
  notify: "restart web server"
- name: enable configuration
  file:
    dest: "/etc/nginx/sites-enabled/{{ conf_file }}"
    src: "/etc/nginx/sites-available/{{ conf_file }}"
    state: link
  notify: "restart web server"
